---
kind: pipeline
type: kubernetes
name: deploy

node_selector:
  kubernetes.io/arch: amd64

steps:
  - name: frontend-build
    image: node:lts-alpine
    commands:
      - cd frontend
      - yarn install
      - yarn run build
    depends_on: []
  - name: frontend-deploy
    image: plugins/netlify
    settings:
      token:
        from_secret: netlify_token
      site:
        from_secret: netlify_site_id
      path: ./frontend/dist
      prod: true
    depends_on:
      - frontend-build
  - name: bridge-publish-arm64
    image: banzaicloud/drone-kaniko
    settings:
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_token
      registry: git.vh7.uk
      repo: jakew/echo-web-bridge
      context: ./bridge
      tags: latest-arm64
      platform: linux/arm64
    depends_on: []
  # - name: bridge-publish-amd64
  #   image: banzaicloud/drone-kaniko
  #   settings:
  #     username:
  #       from_secret: gitea_user
  #     password:
  #       from_secret: gitea_token
  #     registry: git.vh7.uk
  #     repo: git.vh7.uk/jakew/echo-web-bridge
  #     context: /drone/src/bridge
  #     dockerfile: /drone/src/bridge/Dockerfile
  #     tags: latest-amd64
  #     platform: linux/amd64
  #   depends_on:
  #     - bridge-build-arm64

trigger:
  branch:
    - main
    - dev
  event:
    - push
